sidebar:
  outside:
    name: "外层方案规范"
    sub:
      text:
        name: "文案"
        url: "1.1"
      image:
        name: "图片"
        url: "1.2"
      video:
        name: "视频广告"
        url: "1.3"
  ue:
    name: "详情页设计规范"
    sub:
      page:
        name: "公众号文章"
        url: "2.1"
      h5:
        name: "自定义H5页面"
        url: "2.2"
      outside:
        name: "应用下载模版"
        url: "2.3"
      share:
        name: "分享"
        url: "2.4"
      link:
        name: "外链"
        url: "2.5"
  development:
    name: "开发规范"
    sub:
      common:
        name: "通用规范"
        url: "3.1"
      workflow:
        name: "前端工作流"
        url: "3.2"
        url2: "workflow-simple"
      wxmoment:
        name: "通用库"
        url: "3.3"
      test:
        name: "测试要求"
        url: "3.4"
  faq:
    name: "常见问题答疑"
    url: "4.1"


less:
  paths:
    - source/css/_mp/base.less
    - source/css/_mp/doc.less